### ISSUE TITLE
Incorrect fps memory offset

### ISSUE THREAD

**Issue by Kanken6174** [Wunkolo/Thoth#11]
The memory offset in the wiki for the FPS cap ( aka how to enable 120 fps) is outdated (and sadly i think a lot of them are) the correct one as of 30/10/2020 is `0x3425078`. Btw do you have the new offsets somewhere? Updating the other ones would be nice.

**Comment by Wunkolo** [comment]
Ah yea due to the fact that this repo isn't really active anymore, a lot of the offsets aren't going to be valid anymore.
Many offsets are hard-coded at the moment and won't hold up to any of the latest builds
https://github.com/Wunkolo/Osiris/blob/6948f94b5f289b1296fd726ff42ea3d941d02040/Osiris/Modules/LogModule.cpp#L31-L32

I don't have any new offsets myself, as I don't active research Halo 5 Forge at the moment.
