### ISSUE TITLE
Halo 5: Forge- Crash when changing the AR Projectiles

### ISSUE THREAD

**Issue by HDHerrera** [Wunkolo/Thoth#5]
Hi.
So I followed the tutorial for the AR Projectile change.
I've done like the tutorial, and it changed my AR Projectiles to the Tank Shell one.
But, when I change to other type of projectiles, like Fuel Rod, Beam, Red Missile, etc. it crashes. I don't know why, maybe because I don't have my Halo 5: Forge files cracked...any ideas?
Thanks :)

**Comment by DanBreton** [comment]
Hmm, not really sure whats causing your problem since I don't have too much information regarding your issue. 

I'll try work on an application later today when I get some free time to make it a bit easier than using CE.

**Comment by PersonalityPi** [comment]
The problem you are experiencing is because the values written on the proj list page arn't how they are in memory. The one in my tutorial was already flipped for you.  (Any value that has 0x in the wiki often not how it is in memory) For example, 

Lets take the fuel rod for example
0x1B1A3635

You have to flip this before you use it in memory (And remove the 0x.)
So in memory it would be 35 36 1A 1B.
