### ISSUE TITLE
OsirisLauncher doesn't dump game files

### ISSUE THREAD

**Issue by GreenBL** [Wunkolo/Thoth#7]
When I start the launcher , Halo 5 : Forge opens correctly and goes to the main menu.
However the launcher closes immediatly after H5 launches.
I can barely see a green "Succeded" before it closes.
Assuming it's talking about the .dll injection,it's lying.
I can't find the files anywhere in appdata and my available disk size didn't decrease.

It could be an issue for lower end specs only,but you tell me if I'm doing something wrong.

Versions used are 16th and 18th September.

**Comment by Wunkolo** [comment]
Currently Osiris does not feature the code to dump the packages. The previous tool known as "thoth" is what had originally dumped all the files into the packages `LocalState` folder but it has proven to be very very unstable as factors that were thought to be determinant turned out not to be. The dumper will be re-added in a future version. Until then you may find an [older **unsupported** build of Thoth](https://transfer.sh/JH2y6/release.zip) to use to try and dump the files or _find_ an already uploaded dump somewhere.

**Comment by GreenBL** [comment]
I understand.

Hopefully this issue post will be useful to someone.

Thank you.
