### ISSUE TITLE
Releases list is nonfunctional

### ISSUE THREAD

**Issue by EternalDusk** [Wunkolo/Thoth#9]
Didn't know where else to put this, but I can't get Osiris to compile completely on my end, and none of the releases work, all the links are either dead or dont have an actual download.

**Comment by Kanken6174** [comment]
Same, I can't build it either, getting lots of errors

**Comment by Wunkolo** [comment]
The build artifacts had expired since this repo hasn't been updated in quite some time now. I initiated a new build and there's a new build zip file on the AppVeyor now.

Though, this repo isn't exactly some intended for the masses to use as much as it is a _research framework_ for people like me and other people in the ED team to use. Not sure what you're using it for.

**Comment by Kanken6174** [comment]
Thanks for updating the releases, i actually want to take a peek at halo 5 forge's engine and other modding related stuff... Since exuberant mod isn't open source this is my only lead to start... (so yes, i'm using it for research, documentation is quite scarce on this particular game...)
